In [1]:
import pickle
import numpy as np

In [2]:
ohe_sex = pickle.load(open(r'C:\Users\Pranav Wadatkar\Desktop\Python\structured-learning\Pipeline\model\ohe_sex.pkl', "rb"))
ohe_embarked = pickle.load(open(r'C:\Users\Pranav Wadatkar\Desktop\Python\structured-learning\Pipeline\model\ohe_embarked.pkl', "rb"))
clf = pickle.load(open(r'C:\Users\Pranav Wadatkar\Desktop\Python\structured-learning\Pipeline\model\clf.pkl', "rb"))

In [3]:
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([1,"male",10,0,1,20.5,"C"],dtype=object).reshape(1,7)

test_input

array([[1, 'male', 10, 0, 1, 20.5, 'C']], dtype=object)

In [4]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))
test_input_age = test_input[:,2].reshape(1,1)

test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

c:\Users\Pranav Wadatkar\Desktop\Python\structured-learning\venv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [5]:
test_input_embarked

array([[1., 0., 0.]])

In [6]:
test_input_transformed.shape

(1, 10)

In [7]:
pred = clf.predict(test_input_transformed)

pred

array([0])